### PR TITLE
Native image build

### PR DESCRIPTION
**Pull request by asm0dey**
Hi folks, I've slightly changed the native image build to build automatically the full-fledged GUI flavor of the application. I did it only for the GPLv2 flavor because it's a native binary, so nobody can depend on its source and won't have to disclose binaries of their own applications. I've also added Mac amd64 builds.
I had to change the build slightly: it's beneficial to use the Gradle GraalVM plugin because it handles the application resource better, and PlantUML needs a lot of resources to operate according to docs (skins, localization, icons, etc.). However, be aware that the build of native image will work only on [Liberica NIK](https://bell-sw.com/pages/downloads/native-image-kit/#nik-23-(jdk-21)), since it's the only GraalVM native image distribution supporting Swing without much additional tuning.
Therefore, if a developer wants to run `./gradlew plantuml-gplv2:nativeCompile` they will need to have Liberica NIK installed and the env GRAALVM_HOME pointing to it, or it should be the default JDK.

To test the result, you can check out the [releases section of my fork](https://github.com/asm0dey/plantuml/releases/tag/1.2024.7beta4)

### CODE REVIEW

**Comment by asm0dey** [comment]
Currently, the build fails, because we can't build native image for Java 8, is it possible to work this issue around? My belief is we don't actually care about the Java version of the native binary because a user is not intended to have Java installed to run the native image.

**Comment by arnaudroques** [comment]
Yes, you can try with a more recent version of java for the native build.

**Comment by asm0dey** [comment]
Yes, if you look at my changes in the PR, the native image uses Java 21 and works correctly (I think). But here I can't force 8 on ubuntu-latest to pass

**Comment by arnaudroques** [comment]
> I would be grateful for any comments on what I should do to have this PR integrated

Yes, sorry, the team is off for a couple of weeks...
We are going to look at this PR carefully at the end of the month.

Sorry again for the delay, but thanks for your work!

**Comment by asm0dey** [comment]
Nothing to be sorry for, I just wasn't sure if anybody is interested (which is also perfectly fine, I can support my own fork for this matter).
Thank you for attention!

**Comment by asm0dey** [comment]
Folks, I'm sorry, but I am not sure that the workflow file should remain as I changed it. Currently it pushes the native image to the tag automatically on every push. Is it a desired behavior?

**Comment by arnaudroques** [comment]
So, we ended up doing something very simple: we excluded Java 8 from the GPLv2 tests and build!  
We're open to better ideas if anyone have any suggestions.

Anyway, thanks again for your contribution and patience!

> Folks, I'm sorry, but I am not sure that the workflow file should remain as I changed it. Currently it pushes the native image to the tag automatically on every push. Is it a desired behavior?

I think it's fine because it is then published as a beta on [GitHub Releases](https://github.com/plantuml/plantuml/releases).
I guess that when the official 1.2024.7 release is published, further pushes won't overwrite it because we'll first increase the version number right after the release.

@The-Lum, any thoughts on this?

**Comment by asm0dey** [comment]
It should be absolutely safe, no releases will be lost, but there is a chance that the source code in the release won't match binaries

**Comment by The-Lum** [comment]
Hi @asm0dey, @arnaudroques, and all,

About:
>@The-Lum, any thoughts on this?

- What are your main goal?
- What is the architecture? on each pushes? on each pre-release? with tag? on release? on pre-release?

Perhaps to avoid to affect the normal release _(see #1881)_, it will be necessary to create, as the [snapshot](https://github.com/plantuml/plantuml/releases/tag/snapshot), 
a tag `native` _(and not a release, but more a pre-release)_ and put the native output on each pushes or changes?

_To debate,_
Regards,
Th.

**Comment by The-Lum** [comment]
Hi @asm0dey, @arnaudroques, and all,

FYI there are some issues on "win native" creation:
- https://github.com/plantuml/plantuml/actions/runs/10557634039/job/29245545352#step:13:13

```
/usr/bin/tar: C\:/Users/runneradmin/.gradle/caches/modules-2/modules-2.lock: Read error at byte 0, while reading 38 bytes: Device or resource busy
/usr/bin/tar: Exiting with failure status due to previous errors
Warning: Failed to save: "C:\Program failed with error: The process 'C:\Program Files\Git\usr\bin\tar.exe' failed with exit code 2
Cache saved with the key: setup-graalvm-Windows-gradle-1178db426b67b175898d7651ff7b915c5dbbd49cc98a00eabfb545b9d0a36773
```

If you can check?

Regards,
Th.

**Comment by asm0dey** [comment]
@The-Lum it's to be reported to the upstream, I think. As you can see it's in the "post" phase of the "setup graalvm" action, it's not under our control and we can do nothing about it as far as I understand.
As long as windows native build works correctly it's not a big issue too

**Comment by The-Lum** [comment]
@asm0dey Thanks for this precision. 👍 

I just saw the error (wihtout any analyse) on:
- https://github.com/plantuml/plantuml/actions/runs/10557634039



Regards,
Th.

**Comment by asm0dey** [comment]
> What is the architecture? on each pushes? on each pre-release? with tag? on release? on pre-release?

The current implementation publishes artifacts on push, I think it's totally fine, there is no need in any complex procedure like Maven central publication and it allows users to try pre-release versions early of they will.
However I also think we should publish native builds in releases too! SaaS's like kroki, planttext and others might be interested in this in my opinion.

**Comment by The-Lum** [comment]
> However I also think we should publish native builds in releases too!

You are right...

_[And Just for the record]_
Here are some attempts to add native version on Release:
- #1345
- #1360
- #1362
- #1385
- #1391

See aslo this old or standby PR:
- #1395

And here is the original requests about _native_:
- #1344
- #1392


_[FYI @ggrossetie, @evantill, @bcopy: current work about native version of PlantUML...]_

_Thanks for all your contribution,_
Regards,
Th.

**Comment by The-Lum** [comment]
@asm0dey 
> It should be absolutely safe, no releases will be lost, but there is a chance that the source code in the release won't match binaries

It seems there is a issue.
Native images ([_native_](https://github.com/plantuml/plantuml/releases/tag/native)) are updated (and overridden) well on each push but not the sources.

Do you know if with [svenstaro/upload-release-action](https://github.com/svenstaro/upload-release-action) it is possible to update source also?

Regards,
Th.

**Comment by asm0dey** [comment]
I mentioned it :)

> the source code in the release won't match binaries

I think for this to work we should delete a tag and set it on the new HEAD. It's just how GitHub releases work

**Pull request merged**
