### PR TITLE
Add plainImageBuilder() plainPngBuilder() styledImageBuilder() and PlainDiagram / PlainStringsDiagram classes.

### PR DESCRIPTION
**Pull request by matthew16550**
As discussed in #501, it's points 1, 4 & part of 5.

This ended up bigger than I was hoping for, kept getting confused trying to do it in smaller chunks.

### CODE REVIEW

**Comment by matthew16550** [comment]
I'll pause until the release is done.  Don't want to change too much on a separate branch then have a big confusing merge.

**Comment by arnaudroques** [comment]
The release is done !

**Comment by matthew16550** [comment]
Messed up git in this one 🤦

**Comment by matthew16550** [comment]
Trying again in #504

**Pull request closed without merging**
