### PR TITLE
Move preserveAspectRatio & svgLinkTarget calculation to ImageBuilder class

### PR DESCRIPTION
**Pull request by matthew16550**
As discussed in #501.

### CODE REVIEW

**Comment by arnaudroques** [comment]
It's not a big deal, but I think there is a slight regression on `preserveAspectRatio`.

On SVG, older version outputs `preserveAspectRatio="none"` whereas refactored one outputs now `preserveAspectRatio=""`.

Can you confirm this change ?
Thanks !

**Comment by matthew16550** [comment]
I still get `preserveAspectRatio="none"`.  What is your test setup?

**Comment by arnaudroques** [comment]
> I still get `preserveAspectRatio="none"`. What is your test setup?

So sorry, I should have give an example. I know it's very frustrating when someone says "it does not work for me" without giving a single clue :-)

```
@startuml
listopeniconic
@enduml
```

or

```
@startcreole
this is an example **which is bold**
@endcreole
```

I think other diagrams are working fine.

**Comment by matthew16550** [comment]
Yes I see it now.  Working on a fix.

**Pull request merged**
