### PR TITLE
Add a new !pragma svginterface <true|false> to control INTERACTIVE mode on SVG output and Add support for interactive mouseover/mouseout focus on SVG to focusing on a node and its edges in a complex diagram.  This is enabled with !pragma svginteractive.

### PR DESCRIPTION
**Pull request by blipper**
Can set to either '!pragma svginterface true' or !pragma svginterface false'.  Will default to false.

### CODE REVIEW

**Comment by blipper** [comment]
Are the CI tests flakey?

**Comment by arnaudroques** [comment]
That's a good idea, but before merging this:

- I don't like `import net.sourceforge.plantuml.*;` so please restore imports
- Instead of using a pragma in the constructor of SvgGraphics, use a boolean.

So instead of:

`long seed, String preserveAspectRatio, LengthAdjust lengthAdjust, DarkStrategy darkStrategy, Pragma pragma) {`

use

`long seed, String preserveAspectRatio, LengthAdjust lengthAdjust, DarkStrategy darkStrategy, boolean interactive) {`

Thansk!

**Comment by blipper** [comment]
Done

**Comment by koppor** [comment]
@blipper Could you maybe change the PR title and the text. It is `!pragma svginteractive true` to enable the feature, not `svginterFACE` (capital letters by me).

**Pull request merged**
