### PR TITLE
update gradle to gradle-8.10, which permits java-22, java-23.

### PR DESCRIPTION
**Pull request by soloturn**
compile works, tests run through.

### CODE REVIEW

**Comment by The-Lum** [comment]
Hi @soloturn, @arnaudroques, 

- Should we also update the [gradle-wrapper.jar](https://github.com/plantuml/plantuml/blob/master/gradle/wrapper/gradle-wrapper.jar) jar?
  - On https://github.com/plantuml/plantuml/tree/b056f45bcd6269f3b455112336735089c04a3576/gradle/wrapper
- or should we exclude it from the repo.?

Regards,
Th.

**Comment by arnaudroques** [comment]
> * Should we also update the [gradle-wrapper.jar](https://github.com/plantuml/plantuml/blob/master/gradle/wrapper/gradle-wrapper.jar) jar?
>   
>   * On https://github.com/plantuml/plantuml/tree/b056f45bcd6269f3b455112336735089c04a3576/gradle/wrapper
> * or should we exclude it from the repo.?

I am really not sure.
Any idea about the best practice? What other Java project are doing?

**Comment by The-Lum** [comment]
Here are some elements:
- https://stackoverflow.com/questions/25769536/how-when-to-generate-gradle-wrapper-files
- https://docs.gradle.org/current/userguide/gradle_wrapper.html
- https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:upgrading_wrapper

Regards,
Th.

**Comment by The-Lum** [comment]
Hi @arnaudroques, @soloturn,

After rapidity search, in fact the CI does not use `gradle-wrapper.jar`, it uses the local `gradle` *_(and it is already on 8.10!)_*... 
- https://github.com/plantuml/plantuml/actions/runs/10768938506/job/29859074155#step:4:19

So there is no impact on the CI, but only on the use by external users of the repository fork.
Then:
- @arnaudroques you can accept this PR as it.
- and we will see later if it is necessary to update `gradle-wrapper.jar`...

Regards,
Th.

**Comment by The-Lum** [comment]
We will ready for gradle 9....
Next step...

**Comment by soloturn** [comment]
@The-Lum  @arnaudroques the wrapper does not change a lot, so it is ok to [upgrade it from time to time, but not always](https://docs.gradle.org/current/userguide/gradle_wrapper.html#:~:text=This%20is%20usually%20fine%20as,wrapper%20task%20a%20second%20time.).

**Comment by The-Lum** [comment]
We can wait Gradle v9...

**Pull request merged**
