### PR TITLE
Add Dockerhub release to GHA

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

### CODE REVIEW

**Comment by gliptak** [comment]
@arnaudroques please validate that below credentials were created at https://github.com/plantuml/plantuml/settings/secrets/actions

secrets.DOCKERHUB_USERNAME
secrets.DOCKERHUB_TOKEN

otherwise the release action might error

this is how my fork looks

image

**Comment by arnaudroques** [comment]
> otherwise the release action might error

Is this really needed?
There is indeed no `DOCKERHUB_TOKEN` and `DOCKERHUB_USENAME` defined but it does not seem to be an issue.

**Comment by arnaudroques** [comment]
> @arnaudroques please validate that below credentials were created at

Sure, thanks again for your help!
So we now have a second repository available at https://hub.docker.com/u/plantuml :-)

It probably needs some documentation :-)

**Comment by gliptak** [comment]
I also attempted to update https://plantuml.com/command-line (might need to approved?)

**Pull request merged**
