### PR TITLE
Fix #635 Link in ref element not displayed

### LINKED ISSUE #635: Link in `ref` element not displayed
## Situation

When adding a link `[[...]]` in a `ref` element of a sequence chart, that link does not appear unless it is prefixed by regular text.

Since links are especially useful in `ref` sections, I think this should work.

## Steps to reproduce

```
@startuml
Participant A
ref over A : [[link does not work]]
ref over A : [[link neither does this]] here
ref over A : see [[link this works]]
@enduml
```

### Reproducibility

100%

### Environment

* Plantuml 8059
* dot - graphviz version 2.43.0 (0)
* Linux 5.11.0-31-generic `#33-Ubuntu SMP Wed Aug 11 13:19:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

### PR DESCRIPTION
**Pull request by gwilherm**

### CODE REVIEW

**Comment by The-Lum** [comment]
As:
- https://github.com/plantuml/plantuml/issues/635#issuecomment-1082354399

Should the URL be moved before the colon?

**Comment by gwilherm** [comment]
Oh, I didn't want to take responsibility to change the syntax

**Comment by The-Lum** [comment]
@arnaudroques: We let you make the decision...

_In order to authorize:_
```puml
@startuml
ref over A : [[link]]
ref over A : [[link]] text on ref
ref over A : text on ref and [[link]]
ref over A [[link]]
ref over A [[link]] : text on ref
@enduml
```

>[](http://www.plantuml.com/plantuml/umla/SoWkIImgAStDuIfAJLF8BqijKd1Ki5A8Zix9pCkEZSKkgb2IMb6Ya9-d09H5KO4ieP2ObuBD7BnYg4PmEQJcfG3T1W00)

http://www.plantuml.com/plantuml/umla/SoWkIImgAStDuIfAJLF8BqijKd1Ki5A8Zix9pCkEZSKkgb2IMb6Ya9-d09H5KO4ieP2ObuBD7BnYg4PmEQJcfG3T1W00

**Comment by gwilherm** [comment]
Wel, i just discovered the existence of "topurl"

**Pull request merged**
