### PR TITLE
Remove maven

### PR DESCRIPTION
**Pull request by soloturn**
you want to remove the maven build or leave it ?

in case remove, this pull request renames the gradle workflow stuff into the original names. and removes the maven pom.

### CODE REVIEW

**Comment by arnaudroques** [comment]
Let's try to remove maven...
However, there is [an issue during the upload](https://github.com/plantuml/plantuml/runs/5510343748?check_suite_focus=true):

```
Run .github/scripts/release-gradle-snapshot.sh
  .github/scripts/release-gradle-snapshot.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.2-8/x64
    GITHUB_TOKEN: ***
/home/runner/work/_temp/28d08919-8467-4a87-b84b-e2bc2397046c.sh: line 1: .github/scripts/release-gradle-snapshot.sh: No such file or directory
Error: Process completed with exit code 127.
```

Any idea?

**Comment by soloturn** [comment]
ah, i had that one one only on master but created the PR out of the feature branch, sorry.

**Comment by matthew16550** [comment]
@arnaudroques I have not paid close attention recently.  Do we still need `pom.xml` for releasing to Maven Central?

**Comment by arnaudroques** [comment]
> Do we still need `pom.xml` for releasing to Maven Central?

Frankly, I don't know :-)

But if we go to full gradle, and if gradle does not need  `pom.xml` (which I suspect), then we can remove  `pom.xml` for releasing to Maven Central.

**Comment by matthew16550** [comment]
Unless there is something complicated set up here, Gradle does not need `pom.xml`

Do we know what commands to run when we release `1.2022.3` into Maven Central?

cc @soloturn

**Comment by soloturn** [comment]
how do you plubish currently? i saw there is: https://search.maven.org/artifact/net.sourceforge.plantuml/plantuml. is it:

```
mvn deploy
....
Uploading to sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/net/sourceforge/plantuml/plantuml/1.2022.1-SNAPSHOT/plantuml-1.2022.1-20220313.082801-2.jar
Uploading to sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/net/sourceforge/plantuml/plantuml/1.2022.1-SNAPSHOT/plantuml-1.2022.1-20220313.082801-2.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:18 min
[INFO] Finished at: 2022-03-13T09:29:19+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project plantuml: Failed to deploy artifacts: Could not transfer artifact net.sourceforge.plantuml:plantuml:jar:1.2022.1-20220313.082801-2 from/to sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots/): authentication failed for https://oss.sonatype.org/content/repositories/snapshots/net/sourceforge/plantuml/plantuml/1.2022.1-SNAPSHOT/plantuml-1.2022.1-20220313.082801-2.jar, status: 401 Unauthorized -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

```
?

**Comment by arnaudroques** [comment]
We publish by running maven on a local machine.

But we would like to get rid of this, and to publish through github.
I guess we have to install some secret/token on github to allow publication with gihub action.

**Pull request merged**
