### PR TITLE
Added a crowfoot implementation

### PR DESCRIPTION
**Pull request by bminderh**
so that uml can be (mis) used for database diagrams.

### CODE REVIEW

**Comment by arnaudroques** [comment]
Hi,
Many thanks for your contribution! We're going to add this in next official release. 
Can we cite your name in the to-be "what's new" section ( http://plantuml.com/news ) ?

Thanks again

**Comment by bminderh** [comment]
That's fine, code was organized pretty well. Made it easy to do the
extension.

**Comment by megawubs** [comment]
Is there any documentation on how to use this?

**Comment by bminderh** [comment]
@megawubs I used it like this:

`@startuml
sprite $pk [17x12/16z] bOqv3e1030CJRzPn9Fx_NWY7n4eqJ3TJs6OVa5pTpD-5tl3YyFHG-4DsqAOnWgawWp0r0KGagDuGMYMJxbMrBxzLPJ_O0G00

!define table(x) class x << (T,olive) >>

hide stereotypes

table(person) {
id:int(11)<$pk>
name:char(32)
}

table(car) {
id:int(11)<$pk>
person_id:int(11)
name:char(32)
}
person "0..1" --{ "n" car
@enduml`

**Pull request closed without merging**
