### PR TITLE
feat: add builtin function `%mod` (modulo operator)

### PR DESCRIPTION
**Pull request by dragondive**
This change adds the `%mod` function to perform modulo division between two integers.

### CODE REVIEW

**Comment by dragondive** [comment]
Here are also a couple of "fun" educational examples where I used workarounds for the modulo division:

* Generate the Collatz sequence chains: [Github link](https://github.com/dragondive/plantuml_demo/blob/main/src/preprocessor/README.rst#compute-and-draw-collatz-sequence-for-a-range-of-numbers)
* Colouring a chessboard in alternating colours: [Blog post link](https://dragondive.github.io/2024/07/19/plantuml-compute-diagrams/)

**Comment by The-Lum** [comment]
Hello @dragondive,

Thanks for this contribution.

Could you now update _(if it is possible)_ the documentation with `%mod` here:
- http://alphadoc.plantuml.com/doc/markdown/en/preprocessing
- http://alphadoc.plantuml.com/doc/markdown/en/preprocessing#0umqmmdy1n9yk362kjka

_Thanks,_
Regards,
Th.

**Comment by dragondive** [comment]
> Hello @dragondive,
> 
> Thanks for this contribution.
> 
> Could you now update _(if it is possible)_ the documentation with `%mod` here:
> 
>     * http://alphadoc.plantuml.com/doc/markdown/en/preprocessing
> 
>     * http://alphadoc.plantuml.com/doc/markdown/en/preprocessing#0umqmmdy1n9yk362kjka
> 
> 
> _Thanks,_ Regards, Th.

Sure, I will look through the docs to learn the current structure, then update the docs later in this week. I will update this comment when it is done.

**Comment by dragondive** [comment]
I submitted my update to the documentation a few days ago, but I couldn't load the page history to check its status. So I submitted the same updates again today. Hopefully it gets approved soon.

**Comment by The-Lum** [comment]
Thanks a lot @dragondive

Awaiting @arnaudroques's approval.

Regards,
Th.

**Comment by The-Lum** [comment]
Hi,

Your adding for the document was approved.
Thanks for your contribution.

Regards,
Th.

**Pull request merged**
