### PR TITLE
Proposal : Split the project in smaller modules

### PR DESCRIPTION
**Pull request by evantill**
I would like to split the project in smaller modules to make it easier to work with.

Example of modules coud be : a module for each diagram type, a module for the cli interface etc..

This is the first step : move everything in a module legacy.

What do you think of it ?

### CODE REVIEW

**Comment by evantill** [comment]
The jar compile fine on my computer but I have not tested the release process (I don't know how to test it)

**Comment by arnaudroques** [comment]
Well, you should probably [open a new discussion](https://github.com/plantuml/plantuml/discussions) about what you'd like to achieve.

I'm not sure that we could use modules right now because we want to keep Java 8 compatibility.

BTW, we are also refactoring the project into a better package organization to make it easier to work with, but it's still an ongoing task.

**Comment by evantill** [comment]
ok I will open a new discussion.
My first goal is to split the gradle project into a multi-project build.
By the meantime I will update this PR to show what does it look like.

**Comment by arnaudroques** [comment]
Note also that we need to fix https://github.com/plantuml/plantuml/pull/1135 before changing anything on the build.

For some unknown reason, .asc signature files are not published to https://oss.sonatype.org so we still use maven to build PlantUML

**Comment by evantill** [comment]
I will look at #1135.

**Pull request closed without merging**
