### PR TITLE
Documentation corrections

### PR DESCRIPTION
**Pull request by albert-github**
Some "obvious" code documentation corrections.

### CODE REVIEW

**Comment by albert-github** [comment]
Any possibility to get this pull request merged?

**Comment by arnaudroques** [comment]
We have decided to **not** modify code that is not from us (JCCKit, ACEarth...)
So this merge request cannot be merged.
Sorry about that!

**Comment by albert-github** [comment]
Understandable, but where can I report the problems so you can later on pull those versions and use in plantuml?

**Comment by arnaudroques** [comment]
We've changed our mind :-)
Thanks and sorry for the delay...

**Pull request merged**
