### PR TITLE
Carbon Gray Theme

### PR DESCRIPTION
**Pull request by bharatrajagopalan**
@arnaudroques I originally created a pull request in @bschwarz theme repo (https://github.com/bschwarz/puml-themes/pull/20), but then saw your  instructions on https://plantuml.com/theme to raise the request here, so here it goes

# Theme Name
carbon-gray

# Description
Theme using the gray palette from carbondesignsystem.com (https://carbondesignsystem.com/guidelines/color/overview/#color-anatomy). Looks best when used with the IBM Plex Sans Font (needs to be installed separately)

Some pics: (you can see all the generated svgs in the above pull request)
image
image

### CODE REVIEW

**Comment by arnaudroques** [comment]
Many thanks for your contribution.
This new theme will be included in next official release (next month).

**Comment by bharatrajagopalan** [comment]
Thanks @arnaudroques :). 

Btw is there a process or competition for selecting a default theme for plantuml?

**Comment by The-Lum** [comment]
Hello @bharatrajagopalan, and all,

FYI, the [PlantUML themes Gallery](https://the-lum.github.io/puml-themes-gallery/) was updated with this new theme;
Then if you want to check or watch the output, see here:
- [`carbon-gray theme` on themes Gallery](https://the-lum.github.io/puml-themes-gallery/#carbon-gray)

**Comment by bharatrajagopalan** [comment]
@The-Lum - Thank you.

I noticed that my theme doesn't cover all the different artifacts/diagram types that the gallery generates.So I will be making additions this theme accordingly to cover all the diagram types/shapes.

when I run the build script, it only seems to generate a subset of the svgs and shapes (e.g. the components sag doesn't seem to include the `agent` component and a few others like the Gantt chart.

What should I run to generate the exact output locally as seen on the themes gallery so that I can use that to test before my next pull request?

**Comment by The-Lum** [comment]
Hello @bharatrajagopalan, and all,

>What should I run to generate the exact output locally as seen on the themes gallery so that I can use that to test before my next pull request?

You can test your theme on those PlantUML input files:
- https://github.com/bschwarz/puml-themes/tree/master/examples
- https://github.com/The-Lum/puml-themes-gallery/tree/main/input
_[FYI, one of the main goal, when I decide to create "themes gallery", was to have relevant examples in order to improve theme definition... But it is currently only a sub-set of all the combinations of PlantUML possibilities... To improve step by step...]_
- or other set of possible relevant PlantUML input file...

and a script like:
```sh
java -jar plantuml.jar -tsvg -config ./path_of_your/puml-theme-carbon-gray.puml ./path_of_input/*.puml
```

**Comment by bharatrajagopalan** [comment]
Perfect thank you - I tested this with the first link that you have there , the second one is definitely more comprehensive - will use that going forward

**Pull request merged**
