### PR TITLE
Add Machine and stereotype symbols to Problem Diagrams

### PR DESCRIPTION
**Pull request by yijunyu**
Hi Arnaud,

I just created an extension of PlantUML to draw Problem Diagrams, a rather useful requirements modeling diagram based on Michael Jackson's Problem Frames.
I didn't choose to create a plugin instead, rather I go on with adding two additional packages for the Factory and Command classes, they inherit from the Object Diagrams as a convenience route (may be not the best way to add the extension?) 
Here is an example diagram:
```
@startuml
title Problem Diagram R1
requirement "Collect and display drone flight paths on a map" as R1
domain "Google Map" as D1       <<Designed>>
domain "Onboard LiveBox" as D2  <<Designed>>
domain "Drone"   as D3  <<Biddable>>
domain "Path"    as D4  <<Lexical>>
domain "Map"     as D5  <<Causal>>
domain "Monitor" as M   <<Machine>>
M -- D1:                a1
M -- D2:                b1
D1 -- D4:               d1
D4 <-[dashed]- R1:      d
D2 -- D3:               e1
D3 -[dashed]- R1:       e
D2 -- D4:               d2
D5 <-[dashed]- R1:      c
D1 -- D5:               c1
@enduml
```
Best regards,
Yijun

### CODE REVIEW

**Comment by arnaudroques** [comment]
First, thanks for your code and congratulation for your works!

I've done a quick review, and I have few remarks:

- rather than creating a new Factory (ProblemDiagramFactory.java) and a new Diagram (ProblemDiagram.java), I think it would be better to add your new command CommandCreateMachine.java to DescriptionDiagramFactory.java. DescriptionDiagram is some kind of generic diagram which already supports UseCase/Component/Composite/Archimate diagrams. So it would make sense to add Problem Diagram to it.

- I think we could add some isMachine()/isDesigned()/isLexical()/isCausal()/isBiddable() methods in Stereotype.java to simplify DotDataImageBuilder.java code

I have not finished my review, so I'll post some more message here in the incoming days.

Thanks again

**Comment by arnaudroques** [comment]
Hi Yijun,
So I begin to integrate your code, while refactoring it.
It's going to slightly change what you have written : I try to limit code duplication.
I did not take (yet) what you have done on AbstractBehaviour and AbstractBehaviour2.
I think we should first finish "Problem Diagram"
Does it sound good to you ?

**Comment by yijunyu** [comment]
Thank you for refactoring the code, Please go ahead with your intended changes, which makes a lot of sense to me!

**Comment by soloturn** [comment]
@yijunyu @arnaudroques this one can be closed isn't it?

**Comment by yijunyu** [comment]
Before closing it please as @arnaudroques whether the refactoring has been done, or to be tracked as a separate issue. Thank you anyways!

**Comment by arnaudroques** [comment]
Yes, it can be closed. The initial example is [working by the way](https://www.plantuml.com/plantuml/uml/TOwzRi8m58NtFCLHzWm9i5G88R3KXQY8jUfm4zycbln3RQUYRrySeA8flUlvldlEEaJoSJ0wYofgnjwxHhE1KDHvCZYKcUUFGNasR2FohTEQsmYo4bA5ewOlIEyiurshheyuKkm3d0N1q347XVH3EaFA8dzshjEC-fg84fTRBWK7rLcMgzKF_68RHrvYfpvvuquNe_e75cb43epGB44R9IKrck-W_NbSZYiqJz2EJwebVSUCssxC8Z5R6i9ln5aLdHy7rKX8JMslRAggKHGGvHCcH-Krglv4JPc9SipcqqoUepcMnQkaqBDyAt2ulPQPg4PfDfNuBCtmo04dwN5JbOd5uwRsDcynbTeoMxELWz7V).

**Pull request closed without merging**
